name: test

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Build ext/miniaudio
        run: make -C ext
      - name: Run specs
        run: crystal spec --error-trace
